# Inserts a blank line between shell prompts
# ç©ºè¡Œè¿½åŠ 
add_newline = true

# ã‚¿ã‚¤ãƒ ã‚¢ã‚¦ãƒˆæ™‚é–“
scan_timeout = 1000
command_timeout = 1000

# "â¯" è¨˜å·ã‚’ "âœ" è¨˜å·ã«ç½®ãæ›ãˆã¾ã™
[character]                            # è¨­å®šã—ã‚ˆã†ã¨ã—ã¦ã„ã‚‹ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã®åå‰ã¯ "character" ã§ã™ã€‚
#success_symbol = "[âœ](bold green)"     # "success_symbol" ã‚»ã‚°ãƒ¡ãƒ³ãƒˆãŒã€Œå¤ªå­—ã®ç·‘è‰²ã€ã‚¹ã‚¿ã‚¤ãƒ«ã® "âœ" ã«è¨­å®šã•ã‚Œã¦ã„ã¾ã™

# success_symbol = "ğŸ™†â€â™‚ï¸"
# error_symbol = "ğŸ™…â€â™€ï¸"

# success_symbol = "[â†’](bg:#0000cd fg:#ff1493)"
# error_symbol = "[â†](bg:#00ff00 fg:#4b0082)"

success_symbol = "[â–¶](bold green)" # ã‚³ãƒãƒ³ãƒ‰æˆåŠŸæ™‚
error_symbol = "[â–¶](bold red)"    # ã‚³ãƒãƒ³ãƒ‰å¤±æ•—æ™‚

# packageãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’ç„¡åŠ¹ã«ã—ã€ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã‹ã‚‰å®Œå…¨ã«éš ã—ã¾ã™
[package]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false

[git_status]
disabled=true

# ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªã‚’ãƒ•ãƒ«ãƒ‘ã‚¹è¡¨ç¤º
[directory]
truncation_length = 100
truncate_to_repo = false

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[time]
disabled = false
format = 'â°:[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "10:00:00-14:00:00"
